package io.cess.sample.ws.service; /**
 * Created by lin on 9/1/16.
 */
import java.util.logging.Logger;

/**
 * Examples code for spring boot with CXF services. sample.HelloPortImpl is the
 * implementation for sample.Hello interface. This class was generated by Apache CXF
 * 3.1.0 2015-05-18T13:02:03.098-05:00 Generated source version: 3.1.0
 */

//@javax.jws.WebService(serviceName = "HelloService2", portName = "HelloPort",
//        targetNamespace = "http://service.ws.sample.lin/",
//        endpointInterface = "lin.sample.ws.service.Hello")
public class HelloPortImpl implements Hello {

    private static final Logger LOG = Logger.getLogger(HelloPortImpl.class.getName());

    public java.lang.String sayHello(java.lang.String myname) {
        LOG.info("Executing operation sayHello" + myname);
        try {
            return "sample.Hello, Welcome to CXF Spring boot " + myname + "!!!";

        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}